// Generated by gencpp from file visual_servo/circle1.msg
// DO NOT EDIT!


#ifndef VISUAL_SERVO_MESSAGE_CIRCLE1_H
#define VISUAL_SERVO_MESSAGE_CIRCLE1_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace visual_servo
{
template <class ContainerAllocator>
struct circle1_
{
  typedef circle1_<ContainerAllocator> Type;

  circle1_()
    : header()
    , name()
    , radius(0.0)
    , center_x(0.0)
    , center_y(0.0)  {
    }
  circle1_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , radius(0.0)
    , center_x(0.0)
    , center_y(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef float _radius_type;
  _radius_type radius;

   typedef float _center_x_type;
  _center_x_type center_x;

   typedef float _center_y_type;
  _center_y_type center_y;





  typedef boost::shared_ptr< ::visual_servo::circle1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visual_servo::circle1_<ContainerAllocator> const> ConstPtr;

}; // struct circle1_

typedef ::visual_servo::circle1_<std::allocator<void> > circle1;

typedef boost::shared_ptr< ::visual_servo::circle1 > circle1Ptr;
typedef boost::shared_ptr< ::visual_servo::circle1 const> circle1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visual_servo::circle1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visual_servo::circle1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::visual_servo::circle1_<ContainerAllocator1> & lhs, const ::visual_servo::circle1_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name &&
    lhs.radius == rhs.radius &&
    lhs.center_x == rhs.center_x &&
    lhs.center_y == rhs.center_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::visual_servo::circle1_<ContainerAllocator1> & lhs, const ::visual_servo::circle1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace visual_servo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::visual_servo::circle1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visual_servo::circle1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visual_servo::circle1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visual_servo::circle1_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visual_servo::circle1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visual_servo::circle1_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visual_servo::circle1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad34fcda4d5e7bd900535ed16cea96de";
  }

  static const char* value(const ::visual_servo::circle1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad34fcda4d5e7bd9ULL;
  static const uint64_t static_value2 = 0x00535ed16cea96deULL;
};

template<class ContainerAllocator>
struct DataType< ::visual_servo::circle1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visual_servo/circle1";
  }

  static const char* value(const ::visual_servo::circle1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visual_servo::circle1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string name\n"
"float32 radius\n"
"float32 center_x\n"
"float32 center_y\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::visual_servo::circle1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visual_servo::circle1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.radius);
      stream.next(m.center_x);
      stream.next(m.center_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct circle1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visual_servo::circle1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visual_servo::circle1_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
    s << indent << "center_x: ";
    Printer<float>::stream(s, indent + "  ", v.center_x);
    s << indent << "center_y: ";
    Printer<float>::stream(s, indent + "  ", v.center_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISUAL_SERVO_MESSAGE_CIRCLE1_H
