// Generated by gencpp from file visual_servo/circle.msg
// DO NOT EDIT!


#ifndef VISUAL_SERVO_MESSAGE_CIRCLE_H
#define VISUAL_SERVO_MESSAGE_CIRCLE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace visual_servo
{
template <class ContainerAllocator>
struct circle_
{
  typedef circle_<ContainerAllocator> Type;

  circle_()
    : header()
    , u(0.0)
    , v(0.0)
    , depth(0.0)  {
    }
  circle_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , u(0.0)
    , v(0.0)
    , depth(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _u_type;
  _u_type u;

   typedef float _v_type;
  _v_type v;

   typedef float _depth_type;
  _depth_type depth;





  typedef boost::shared_ptr< ::visual_servo::circle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visual_servo::circle_<ContainerAllocator> const> ConstPtr;

}; // struct circle_

typedef ::visual_servo::circle_<std::allocator<void> > circle;

typedef boost::shared_ptr< ::visual_servo::circle > circlePtr;
typedef boost::shared_ptr< ::visual_servo::circle const> circleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visual_servo::circle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visual_servo::circle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::visual_servo::circle_<ContainerAllocator1> & lhs, const ::visual_servo::circle_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.u == rhs.u &&
    lhs.v == rhs.v &&
    lhs.depth == rhs.depth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::visual_servo::circle_<ContainerAllocator1> & lhs, const ::visual_servo::circle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace visual_servo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::visual_servo::circle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visual_servo::circle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visual_servo::circle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visual_servo::circle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visual_servo::circle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visual_servo::circle_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visual_servo::circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19441ccc19436b3bb7eded013d980ace";
  }

  static const char* value(const ::visual_servo::circle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19441ccc19436b3bULL;
  static const uint64_t static_value2 = 0xb7eded013d980aceULL;
};

template<class ContainerAllocator>
struct DataType< ::visual_servo::circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visual_servo/circle";
  }

  static const char* value(const ::visual_servo::circle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visual_servo::circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 u\n"
"float32 v\n"
"float32 depth\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::visual_servo::circle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visual_servo::circle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.u);
      stream.next(m.v);
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct circle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visual_servo::circle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visual_servo::circle_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "u: ";
    Printer<float>::stream(s, indent + "  ", v.u);
    s << indent << "v: ";
    Printer<float>::stream(s, indent + "  ", v.v);
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISUAL_SERVO_MESSAGE_CIRCLE_H
