// Generated by gencpp from file visual_servo/toolposeChange.msg
// DO NOT EDIT!


#ifndef VISUAL_SERVO_MESSAGE_TOOLPOSECHANGE_H
#define VISUAL_SERVO_MESSAGE_TOOLPOSECHANGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace visual_servo
{
template <class ContainerAllocator>
struct toolposeChange_
{
  typedef toolposeChange_<ContainerAllocator> Type;

  toolposeChange_()
    : header()
    , pose_change()  {
      pose_change.assign(0.0);
  }
  toolposeChange_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pose_change()  {
  (void)_alloc;
      pose_change.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 16>  _pose_change_type;
  _pose_change_type pose_change;





  typedef boost::shared_ptr< ::visual_servo::toolposeChange_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::visual_servo::toolposeChange_<ContainerAllocator> const> ConstPtr;

}; // struct toolposeChange_

typedef ::visual_servo::toolposeChange_<std::allocator<void> > toolposeChange;

typedef boost::shared_ptr< ::visual_servo::toolposeChange > toolposeChangePtr;
typedef boost::shared_ptr< ::visual_servo::toolposeChange const> toolposeChangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::visual_servo::toolposeChange_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::visual_servo::toolposeChange_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::visual_servo::toolposeChange_<ContainerAllocator1> & lhs, const ::visual_servo::toolposeChange_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pose_change == rhs.pose_change;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::visual_servo::toolposeChange_<ContainerAllocator1> & lhs, const ::visual_servo::toolposeChange_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace visual_servo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::visual_servo::toolposeChange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::visual_servo::toolposeChange_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visual_servo::toolposeChange_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::visual_servo::toolposeChange_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visual_servo::toolposeChange_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::visual_servo::toolposeChange_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::visual_servo::toolposeChange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5a8098ef919b80fbbf915fe48b2d32d";
  }

  static const char* value(const ::visual_servo::toolposeChange_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5a8098ef919b80fULL;
  static const uint64_t static_value2 = 0xbbf915fe48b2d32dULL;
};

template<class ContainerAllocator>
struct DataType< ::visual_servo::toolposeChange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "visual_servo/toolposeChange";
  }

  static const char* value(const ::visual_servo::toolposeChange_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::visual_servo::toolposeChange_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[16] pose_change\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::visual_servo::toolposeChange_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::visual_servo::toolposeChange_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pose_change);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct toolposeChange_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::visual_servo::toolposeChange_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::visual_servo::toolposeChange_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose_change[]" << std::endl;
    for (size_t i = 0; i < v.pose_change.size(); ++i)
    {
      s << indent << "  pose_change[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pose_change[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISUAL_SERVO_MESSAGE_TOOLPOSECHANGE_H
